GET http://localhost:4040/
###

GET http://localhost:4040/api/leaderboard
###

POST http://localhost:4040/api/winner
Content-Type: application/json

{
    "time": 66,
    "moves": 29,
    "user": "Tobias Topp"
}
###