GET http://localhost:4040/
###

GET http://localhost:4040/api/leaderboard
###

POST http://localhost:4040/api/winner
content-type: application/json
{
    "time": 12,
    "moves": 14,
    "user": "Red"
}
###